"""add_reset_token

Revision ID: 629c7e4826fe
Revises: d8e5a74845ea
Create Date: 2026-07-04 05:24:11.947951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629c7e4826fe'
down_revision: Union[str, None] = 'd8e5a74845ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('social_github', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('social_linkedin', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('social_instagram', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('profiles', 'social_instagram')
    op.drop_column('profiles', 'social_linkedin')
    op.drop_column('profiles', 'social_github')
    # ### end Alembic commands ###
