"""Add Program Models

Revision ID: 6f7374a1b0e2
Revises: f03323b8fe52
Create Date: 2026-07-01 05:02:20.958808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7374a1b0e2'
down_revision: Union[str, None] = 'f03323b8fe52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_catalog_id'), 'programs_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_programs_catalog_name'), 'programs_catalog', ['name'], unique=False)
    op.create_table('user_accepted_programs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs_catalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'program_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accepted_programs')
    op.drop_index(op.f('ix_programs_catalog_name'), table_name='programs_catalog')
    op.drop_index(op.f('ix_programs_catalog_id'), table_name='programs_catalog')
    op.drop_table('programs_catalog')
    # ### end Alembic commands ###
